// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: campaigns_sources.sql

package db

import (
	"context"
)

const createCampaignSourceLink = `-- name: CreateCampaignSourceLink :exec
insert into campaigns_sources(source_id, campaign_id) values (?, ?)
`

type CreateCampaignSourceLinkParams struct {
	SourceID   uint64 `json:"source_id"`
	CampaignID uint64 `json:"campaign_id"`
}

func (q *Queries) CreateCampaignSourceLink(ctx context.Context, arg *CreateCampaignSourceLinkParams) error {
	_, err := q.db.ExecContext(ctx, createCampaignSourceLink, arg.SourceID, arg.CampaignID)
	return err
}
