// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: misc.sql

package db

import (
	"context"
)

const getNamesOfCampaignsAndSources = `-- name: GetNamesOfCampaignsAndSources :many
select c.name from campaigns c
union
select s.name from sources s
`

func (q *Queries) GetNamesOfCampaignsAndSources(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getNamesOfCampaignsAndSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
