// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type Campaign struct {
	ID   uint64 `json:"id"`
	Name string `json:"name"`
}

type CampaignsSource struct {
	CampaignID uint64 `json:"campaign_id"`
	SourceID   uint64 `json:"source_id"`
}

type Source struct {
	ID   uint64 `json:"id"`
	Name string `json:"name"`
}
