// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateCampaign(ctx context.Context, name string) error
	CreateCampaignSourceLink(ctx context.Context, arg *CreateCampaignSourceLinkParams) error
	CreateSource(ctx context.Context, name string) error
	GetCampaignsWithoutSources(ctx context.Context) ([]GetCampaignsWithoutSourcesRow, error)
	GetNamesOfCampaignsAndSources(ctx context.Context) ([]string, error)
	GetSourcesWithMostCampaigns(ctx context.Context) ([]GetSourcesWithMostCampaignsRow, error)
}

var _ Querier = (*Queries)(nil)
